apiVersion: v1
kind: Service
metadata:
  name: rnlobby-rlsrvcode-loadbalancer
spec:
  selector:
    app: rlsrvcode
  ports:
    - protocol: UDP
      port: 4003
      targetPort: 4003
  type: LoadBalancer
