apiVersion: v1
kind: Service
metadata:
  name: rnlobby-rlsrvudprelay-loadbalancer
spec:
  selector:
    app: rlsrvudprelay
  ports:
    - protocol: UDP
      port: 4011
      targetPort: 4011
  type: LoadBalancer
