apiVersion: v1
kind: Service
metadata:
  name: rnlobby-rlsrvstat-loadbalancer
spec:
  selector:
    app: rlsrvstat
  ports:
    - protocol: UDP
      port: 4010
      targetPort: 4010
  type: LoadBalancer
