apiVersion: v1
kind: Service
metadata:
  name: rnlobby-rlsrvbackend-loadbalancer
spec:
  selector:
    app: rlsrvbackend
  ports:
    - protocol: UDP
      port: 4000
      targetPort: 4000
      name: udp-4000
    - protocol: UDP
      port: 4001
      targetPort: 4001
      name: udp-4001
  type: LoadBalancer
