apiVersion: apps/v1
kind: Deployment
metadata:
  name: rnlobby-rlsrvstat-deployment
  labels:
    app: rlsrvstat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rlsrvstat
  template:
    metadata:
      labels:
        app: rlsrvstat
    spec:
      containers:
      - name: rlsrvstat
        image: martinpiper/rnlobbydockerservices-app:0.0.1
        command: ["RLSrvStat"]
        args: ["/d", "-dstart"]
        ports:
        - containerPort: 4010
          protocol: "UDP"
        resources:
          requests:
            cpu: 200m
            memory: 300M
          limits:
            memory: 400M
            
