apiVersion: v1
kind: Service
metadata:
  name: rnlobby-rlsrvuser-loadbalancer
spec:
  selector:
    app: rlsrvuser
  ports:
    - protocol: UDP
      port: 4009
      targetPort: 4009
  type: LoadBalancer
