ReplicaNet and RNLobby: SysTime Class Reference
SysTime Class Reference
#include <SysTime.h>
Public Member Functions
SysTime ()
virtual ~SysTime ()
SysTimeType FloatTime (void)
void Reset (void)
Static Public Member Functions
static unsigned int GetTickCount (void)
static void GetSystemTime (SystemTime *sysTime)
A replacement for the Win32 API GetSystemTime() and struct SYSTEMTIME.
Detailed Description
Enables a high performance timer to be used.
Constructor & Destructor Documentation
SysTime ()
The ctor performs some basic initialisation
virtual ~SysTime () virtual
The dtor makes sure everything is tidy
Member Function Documentation
SysTimeType FloatTime (void)
Read the current time and return the time as a SysTimeType which uses floating point. Use the preprocessor define REPLICANET_TIME_FLOAT or REPLICANET_TIME_DOUBLE to force SysTimeType to be a float or a double. By default the type is double.
Referenced by XPSock_Init(), XPSock_UpdatePerSecondMetrics(), and XPSock_UrgentSend().
static unsigned int GetTickCount (void) static
Returns
The number of milliseconds that have elapsed since the system was started.
void Reset (void)
Resets the time back to zero. Effectively initialising this class again.
Referenced by XPSock_UpdatePerSecondMetrics().