/* START_LICENSE_HEADER

Copyright (C) 2000 Martin Piper, original design and program code
Copyright (C) 2001 Replica Software

This program file is copyright (C) Replica Software and can only be used under license.
For more information visit: http://www.replicanet.com/
Or email: info@replicanet.com

END_LICENSE_HEADER */
#if !defined(AFX_OLEOBJECTS_H__981FA59F_33C4_49A0_B2BF_C56D921724AA__INCLUDED_)
#define AFX_OLEOBJECTS_H__981FA59F_33C4_49A0_B2BF_C56D921724AA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class COLEObject;

/////////////////////////////////////////////////////////////////////////////
// COLEObjects wrapper class

class COLEObjects : public COleDispatchDriver
{
public:
	COLEObjects() {}		// Calls COleDispatchDriver default constructor
	COLEObjects(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	COLEObjects(const COLEObjects& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	COLEObject GetItem(const VARIANT& Item);
	long GetCount();
	void Clear();
	COLEObject Add(const VARIANT& Index, const VARIANT& Key, const VARIANT& source, const VARIANT& objclass);
	void Remove(const VARIANT& Item);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_OLEOBJECTS_H__981FA59F_33C4_49A0_B2BF_C56D921724AA__INCLUDED_)
